kind: pipeline
type: docker
name: build

environment:
  ASDF_DATA_DIR: /drone/src/.asdf
  ASDF_DIR: /root/.asdf
  CARGO_HOME: /drone/src/.cargo

steps:
  - name: restore ASDF cache
    image: meltwater/drone-cache
    pull: always
    settings:
      restore: true
      backend: filesystem
      cache_key: '{{ checksum ".tool-versions" }}'
      remote_root: asdf
      mount:
        - .asdf
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install ASDF
    image: harton.dev/james/asdf_container:latest
    pull: always
    depends_on:
      - restore ASDF cache
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - asdf_install
      - asdf reshim

  - name: store ASDF cache
    depends_on:
      - install ASDF
    image: meltwater/drone-cache
    pull: never
    settings:
      rebuild: true
      backend: filesystem
      cache_key: '{{ checksum ".tool-versions" }}'
      remote_root: asdf
      mount:
        - .asdf
    volumes:
      - name: cache
        path: /tmp/cache

  - name: restore build cache
    image: meltwater/drone-cache
    pull: never
    settings:
      restore: true
      backend: filesystem
      cache_key: '{{ checksum ".tool-versions" }}/{{ checksum "Cargo.lock" }}'
      remote_root: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/build
      mount:
        - .cargo
        - target
    volumes:
      - name: cache
        path: /tmp/cache

  - name: setup
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - restore build cache
      - install ASDF
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - rustup component add clippy

  - name: tree-sitter grammar
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - setup
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cd editor-support/tree-sitter-outrun
      - tree-sitter generate
      - echo "Testing grammar with sample files..."
      - tree-sitter parse test.outrun > /dev/null 2>&1 && echo "✓ test.outrun parsed successfully" || echo "✗ test.outrun failed to parse"
      - tree-sitter parse ../../outrun-core/lib/list.outrun > /dev/null 2>&1 && echo "✓ list.outrun parsed successfully" || echo "✗ list.outrun failed to parse"
      - tree-sitter parse ../../outrun-core/lib/option.outrun > /dev/null 2>&1 && echo "✓ option.outrun parsed successfully" || echo "✗ option.outrun failed to parse"

  - name: build
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - tree-sitter grammar
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cargo fetch
      - cargo test --no-run --release

  - name: store build cache
    depends_on:
      - build
    image: meltwater/drone-cache
    pull: never
    settings:
      rebuild: true
      backend: filesystem
      cache_key: '{{ checksum ".tool-versions" }}/{{ checksum "Cargo.lock" }}'
      remote_root: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/build
      mount:
        - .cargo
        - target
    volumes:
      - name: cache
        path: /tmp/cache

  - name: cargo test
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - build
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cargo test --jobs 1 --release

  - name: cargo clippy
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - build
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cargo clippy --all-targets --all-features -- -D warnings

  - name: cargo fmt
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - build
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cargo fmt --check

  - name: website check
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - install ASDF
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cd website
      - zola check

  - name: website build
    image: harton.dev/james/asdf_container:latest
    pull: never
    depends_on:
      - website check
    commands:
      - export PATH="$ASDF_DATA_DIR/shims:$PATH"
      - cd website
      - zola build

  - name: website deploy
    image: node:latest
    when:
      branch:
        - main
      event:
        - push
    depends_on:
      - website build
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
    commands:
      - npx wrangler pages deploy website/public --project-name=outrunlang --commit-dirty --branch=prod


volumes:
  - name: cache
    host:
      path: /tmp/drone-cache
