[workspace]

members = [
  "outrun",
  "outrun-interpreter",
  "outrun-parser",
  "outrun-typechecker",
]

# Exclude the old interpreter from workspace (kept as reference material)
exclude = [
  "outrun-interpreter.old",
]

resolver = "3"
