[package]
name = "outrun-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
outrun-parser = { path = "../outrun-parser" }
outrun-typechecker = { path = "../outrun-typechecker" }
miette = "7.0"
thiserror = "1.0"
