[package]
name = "outrun"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
outrun-parser = { path = "../outrun-parser" }
miette = { version = "7.0", features = ["fancy"] }
