[package]
name = "outrun-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.8"
pest_derive = "2.8"
miette = { version = "7.0", features = ["fancy", "syntect-highlighter"] }
thiserror = "2.0"
